NUMB

In [2]:
x = 67
print(x, type(x))

67 <class 'int'>


Booleans

In [ ]:
t, f = True, False
print(type(t))

Strings

In [3]:
greet = 'greet'   
welcome = "welcome"   # or double quotes; it does not matter
print(welcome, len(greet))

welcome 5


Loops

In [7]:
sports = ['badminton','foot ball', 'cricket']
for sports in sports:
    print(sports) 

badminton
foot ball
cricket


Arrays

In [9]:
import numpy as np
a = np.array([1, 2, 3])  
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


swap 2 varibles without function

In [5]:
def swaped(a,b):
    temp = a
    a = b
    b = temp
    print(a,b)

swaped(a= 1,b = 2)

2 1


Swap using xor

In [6]:
a=5
b=6
a = a^b
b = a^b
a = a^b
print(a)
print(b)

6
5


Get array from user

In [ ]:
from array import array

arr = array('i', [])

n = int(input('Enter the length of the array: '))

for i in range(n):
    x = int(input('Enter the next value: '))
    arr.append(x)

print(arr)

  


Simple matrix multiplication

In [35]:
from numpy import*

m1 = matrix('1 2 3;2 3 4; 1 3 4')
m2 = matrix('8 4 3;2 3 4; 9 7 3')

m3 = m1*m2
 
print(m3)

[[39 31 20]
 [58 45 30]
 [50 41 27]]


Simple Fuction 

In [38]:
def update(x):
    print(x)
    x = 10


x = 5
update(x)

5


Matrix

In [31]:
def matrix_multiplication(A, B):
    
    rows_A = len(A)
    cols_A = len(A[0])
    rows_B = len(B)
    cols_B = len(B[0])

    
    if cols_A != rows_B:
        raise ValueError("Number of columns in A must be equal to the number of rows in B")

    
    result = [[0 for _ in range(cols_B)] for _ in range(rows_A)]

    
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                result[i][j] += A[i][k] * B[k][j]

    return result


A = [[1, 2, 3],
     [4, 5, 6]]

B = [[7, 8],
     [9, 10],
     [11, 12]]


print(matrix_multiplication(A, B))



[[58, 64], [139, 154]]


scope


In [2]:
a = 10

def anything():
    a = 13
    
    print(' in',a)


anything

    
    
print('out',a)    

out 10


Recursion Basics


In [102]:
import sys

sys.setrecursionlimit(1000)

print(sys.getrecursionlimit())

i = 0

def welcome():
    global i
    while i < 20:
        i += 1
        print('thanks', i)

welcome()



1000
thanks 1
thanks 2
thanks 3
thanks 4
thanks 5
thanks 6
thanks 7
thanks 8
thanks 9
thanks 10
thanks 11
thanks 12
thanks 13
thanks 14
thanks 15
thanks 16
thanks 17
thanks 18
thanks 19
thanks 20


Factorial using Recursion

In [41]:
def fact(n):
    if n==0:
       return 1
   
    return n * fact(n-1)

output = fact(9)
print(output)


362880


LAMBDA: Filter, Map, Reduce

In [39]:
from functools import reduce

nums = [3,2,4,6,12,11]

evens = list(filter(lambda n : n%2==0,nums))

double = list(map(lambda n: n*n,evens))

print(double)

add = reduce(lambda a,b : a+b,double)

print(add)


[4, 16, 36, 144]
200


Decorators basics

In [66]:
def div(a ,b):
    print(a / b)
    
def smart_div(func):
        
        def inner(a,b):
            if a<b: 
               a, b = b, a 
            return func(a, b) 
        return  inner

div=  smart_div(div) 
div(2,4)     

2.0


Basics of class

In [73]:
class instr:
    
    def gear(self):
        print('6 gear, 2disc, carbon fiber')
        
bi1 = instr()
bi2 = instr()


bi1.gear() 
bi2.gear()      

6 gear, 2disc, carbon fiber
6 gear, 2disc, carbon fiber


Class variables

In [74]:
class car:
    
    def __init__(self):
        self.cc = 1500
        self.jdm = '4li'
        
c1 = car()
c2 = car()        
        
c1.cc= 2500
print(c1.jdm, c1.cc)

4li 2500


Class Methods

In [83]:
class student:
    
    def __init__(self, ms1, ms2, ms3):
        self.m1 = ms1
        self.m2 = ms2
        self.m3 = ms3
    def avg(self):
            return (self.m1+self.m2+self.m3)/3
    @staticmethod
    def infd():
        print('avg mark of sports student')
            
st1 = student(12, 14, 15) 
st2 = student(18, 17, 16)  
    
print(st1.avg())    
student.infd()      
        
        
        

13.666666666666666
avg mark of sports student


Class within class

In [89]:
class student:
    
    
    def __init__(self,name,rollno):
        self.name = name
        self.rollno = rollno
        self.lap = self.laptop()
    
    def show(self):
        print(self.name, self.rollno)
        self.lap.show()
        
    class laptop:
        def __init__(self):
            self.comp = 'mac'
            self.cpu = '10'
            
        def show():
            print(self.comp, self.cpu)

s1 = student('ashwanth',17) 
s1.show()  


         
            

Ashwanth 17
mac 10


Multi threading

In [96]:
from time import sleep
from threading import *

class hello(Thread):
    def run(self):
        for i in range(2):
            print('greet')
            sleep(1)
            
class welcome(Thread):
     def run(self):
         for i in range(1):
             print('hi')
             
s1 = hello()
s2 = welcome()


s1.start()
sleep(0.5)
s2.start() 
 
print('thanks')                         
    
             

greet
hi
thanks


greet
